version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: web_user
      POSTGRES_PASSWORD: web_pass
      POSTGRES_DB: web_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://web_user:web_pass@db:5432/web_db
